config.set('content.cookies.accept', 'all','*://*.google.com/*')
config.set('content.cookies.accept', 'all','*://*.reddit.com/*')
config.set('content.cookies.accept', 'all','*://web.telegram.org/*')
config.set('content.cookies.accept', 'all','*://web.whatsapp.com/*')
config.set('content.cookies.accept', 'all','*://www.facebook.com/*')
config.set('content.cookies.accept', 'all','*://www.instagram.com/*')
config.set('content.cookies.accept', 'all','*://*.youtube.com/*')
config.set('content.cookies.accept', 'all','*://login.lut.fi/*')
config.set('content.cookies.accept', 'all','*://moodle.lut.fi/*')
config.set('content.cookies.accept', 'all','*://*.lut.fi/*')
config.set('content.cookies.accept', 'all','*://*.duosecurity.com/*')
config.set('content.cookies.accept', 'all','*://*.mooc.fi/*')
config.set('content.cookies.accept', 'all','*://tmc.mooc.fi/*')
config.set('content.cookies.accept', 'all','*://www.sanakirja.fi/*')
config.set('content.cookies.accept', 'all','*://store.epicgames.com/*')
config.set('content.cookies.accept', 'all','*://alex.aaltoee.fi/*')
#add here cookies whitelist
