#!/bin/bash
# Copyright 2024 [Pallav Shrestha]

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
echo "This will create new squared jpegs for all the jpegs in the directory"
read -p "Type [yes] to continue: " choice
case "$choice" in 
    yes ) echo "Processing..."
        for file in *.jpg; do echo "$file"; squareup -c transparent "$file" "square_${file%.jpg}.png"
    if [ -n $1 ]; then
          magick "square_${file%.jpg}.png" -bordercolor transparent -border ${1:-0}%x${1:-0}% "square_${file%.jpg}.png";
    fi
        done;;
    * ) echo "Cancelled";;
esac
