#!/bin/bash

# Copyright 2024 [Pallav Shrestha]

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Original script by Conner McDaniel
# https://github.com/connermcd/bin

set -e

result=
i=
while [[ $i < 10 && "$result" != *"author = "* ]]; do
    result=$(curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex")
    i=$(( $i + 1 ))
done
echo "$result"
