#!/bin/bash

status=$(cat /sys/class/drm/card1/card1-HDMI-A-1/status)
if [[ $status == "connected" ]]; then
    notify-send "HDMI detected"
      left-screen
      echo success 1
else
    edp
    echo success 2
fi

