#!/usr/bin/env bash

rename_files() {
    for item in "$1"/*; do
        # echo "$item"
        new_name1=$(echo "$item" | tr ' ' '_')
        new_name=$(echo "$new_name1" | sed 's/^\(.\)/\l\1/')
        # echo $new_name
        if [ "$item" != "$new_name" ]; then
            mv "$item" "$new_name"
            echo "Renamed: '$item' to '$new_name'"
        # else
        #     echo "$item = $new_name"                
        fi
    done
}

if [ $# -gt 1 ]; then
    echo "Usage: $0 [directory|file]"
    exit 1
fi

target=${1:-.}

if [ -d "$target" ]; then
    # echo "is dir"
    new_name=$(echo "$target" | tr ' ' '_' | sed 's/^\(.\)/\l\1/')
    echo "New_name= $new_name"
    if [ "$target" != "$new_name" ]; then
        mv "$target" "$new_name"
        echo "Renamed: '$target' to '$new_name'"
    fi
    rename_files "$new_name"
elif [ -f "$target" ]; then
    new_name=$(echo "$target" | tr ' ' '_' | sed 's/^\(.\)/\l\1/')
    if [ "$target" != "$new_name" ]; then
        mv "$target" "$new_name"
        echo "Renamed: '$target' to '$new_name'"
    fi
else
    echo "'$target' is not a valid file or directry."
    exit 1
fi
