#!/bin/bash

# Original Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license

set -e

pdf="$(realpath $1)"
doi="$(pdf2doi ${1})"
bib=$(curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex")
if [[ $bib == *"Resource not found"* ]]
then
    title=$(basename -a $pdf)
    title=${title%.*}
else
    title=$(echo "$bib" | sed -n '1p' | cut -d{ -f2 | sed 's/,//')
fi

file_name=

make_file() {
new_pdf="$(dirname $pdf)/$title.pdf"
[[ ! -f "$new_pdf" ]] && mv "$pdf" "$new_pdf"
bib=$(echo "$bib" | sed "1a\\\tpdf = {$new_pdf},")
cat >"$file_name" <<EOF
~~~.bib
$bib
~~~

# Summary

# Quotes and Data

# Questions
EOF
}

check_file() {
    file="$HOME/work/notebooks/papers/$1.md"    #change this according your file structure
    if [[ -f $file ]]; then
        file_doi=$(grep -o -E "doi = {[^}]*" $file | cut -d{ -f2)
        if [[ "${file_doi,,}" =~ "${doi,,}" ]]; then
            file_name="$file"
        else
            check_file "${1}+"
        fi
    else
        file_name="$file"
        make_file "$1"
    fi
}

check_file "$title"
vim "$file_name"
