#!/bin/bash

# Copyright 2024 [Pallav Shrestha]

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Original script by Conner McDaniel
# https://github.com/connermcd/bin

set -e

cd $HOME/work/notebooks/papersRev/

[[ -f tags ]] && rm tags
grep --exclude="*.bib" -r "tags = {" * | while read line; do
    file=$(echo "$line" | cut -d: -f1)
    unparsed_tags=$(echo "$line" | cut -d: -f2)
    tags=$(echo $unparsed_tags | sed -e "s/tags = {//g" -e "s/,\|}//g")
    for tag in $tags; do
        echo "$tag	$file	/^$unparsed_tags$/;" >> tags
    done
done

[[ -f global.bib ]] && rm global.bib
pcregrep -r -M -I --exclude-dir=img --exclude=".*pdf" "^@(\n|.)*~~~" . > global.bib
bibtool -s -q global.bib -o global.bib

