#!/usr/bin/env bash

open='hide xdg-open'   # this will open pdf file withthe default PDF viewer on KDE, xfce, LXDE and perhaps on other desktops. 

# using silver searcher # ag -U -g ".pdf$" \
# useing ripgrep
    rg --files --glob '*.pdf' \
    | fast-p \
    | fzf --read0 --reverse --no-multi-line -e -d $'\t'  \
        --preview-window up:60% \
        --preview '
            v=$(echo {q} | tr " " "|");
            echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always;
            ' \
            | cut -z -f 1 -d $'\t'| xargs -0 -I {} $open "{}"
