#!/usr/bin/env bash

open='xdg-open'   # this will open pdf file withthe default PDF viewer on KDE, xfce, LXDE and perhaps on other desktops.

    # ag -U -g ".pdf$" \  # using silver searcher
    rg --files --glob '*.pdf' \  # using ripgrep
    | fast-p \
    | fzf --read0 --reverse --no-multi-line -e -d $'\t'  \
        --preview-window up:60% \
        --preview '
            v=$(echo {q} | tr " " "|");
            echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always;
            ' \
    | cut -z -f 1 -d $'\t' | tr -d '\n' | xargs -r --null $open > /dev/null 2> /dev/null
 
