#!/bin/sh

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    wlr-randr --output HDMI-A-1 --right-of eDP-1
elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-1 --mode 1920x1080 --pos 1920x0 --rotate normal
else 
    echo "unknown session type"
    notify-send "unknown session type"
    exit 1
fi

echo "Default HDMI-1 position: Right"
notify-send "Default HDMI-1 position: Right"
