#!/bin/bash
# Copyright 2024 [Pallav Shrestha]

# simple scripts to count todos, including dones
# todos are written in this format
# [ ]TODO: 
# [x]TODO: done
#
#
if [ -z "$1" ]; then
    rg todo:
    echo
    echo $(rg todo:|wc -l) "tasks"
    echo $(rg x\]todo:|wc -l) "completed"
    echo $(rg  \]todo:|wc -l) "remaining"
else 
    rg -numbers todo: "$1"
    echo
    echo $(rg todo: "$1"|wc -l) "todos"
    echo $(rg x\]todo: "$1"|wc -l) "done"
    echo $(rg ' \]todo:' "$1"|wc -l) "remaining"
fi

