#!/usr/bin/env bash

# Current Theme
dir="$HOME/.config/rofi/themes/"
theme='powermenu-app'

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostname`

# Options
shutdown=' '
reboot=' '
lock=''
suspend=' '
logout=' '
yes=''
no=' '

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}


# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
		if [[ $1 == '--shutdown' ]]; then
			systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			systemctl reboot
        elif [[ $1 == '--lock' ]]; then
            swaylock -i ~/.config/dogagawa1080.png
		elif [[ $1 == '--suspend' ]]; then
			mpc -q pause
			amixer set Master mute
			systemctl suspend-then-hibernate
		elif [[ $1 == '--logout' ]]; then
			niri msg action quit --skip-confirmation
		fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
		swaylock -i ~/.config/dogagawa1080.png
        ;;
    $suspend)
		run_cmd --suspend-then-hibernate
        ;;
    $logout)
		run_cmd --logout
        ;;
esac

